### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by TheSodaPopPanda** [Fuzss/mobplaques#15]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

this may be compatibility issues with https://www.curseforge.com/minecraft/mc-mods/the-hordes
I noticed this issue when I died with a zombie grave spawned and for some reason it failed to render the name tag and crash the client when getting close to the mob

### Crash Report (Required)

https://gist.github.com/TheSodaPopPanda/5af1cacab78160140ddec1528ecad246

**Comment by TheSodaPopPanda** [comment]
Apologies after further testing I believe this to be an  issue with hordes...

```
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.minecraft.network.chat.Component.getString()" because "p_114499_" is null
	at net.minecraft.client.renderer.entity.EntityRenderer.m_7649_(EntityRenderer.java:88) ~[client-1.20.1-20230612.114412-srg.jar%23814!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.EntityRenderer.m_7392_(EntityRenderer.java:69) ~[client-1.20.1-20230612.114412-srg.jar%23814!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.LivingEntityRenderer.m_7392_(LivingEntityRenderer.java:136) ~[client-1.20.1-20230612.114412-srg.jar%23814!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.MobRenderer.m_7392_(MobRenderer.java:45) ~[client-1.20.1-20230612.114412-srg.jar%23814!/:?] {re:classloading,pl:connector_pre_launch:A,re:mixin,pl:connector_pre_launch:A}
	at net.smileycorp.hordes.client.render.ZombiePlayerRenderer.render(ZombiePlayerRenderer.java:64) ~[The-Hordes-1.20.1-1.3.2b.jar%23767!/:1.20.1-1.3.2b] {re:classloading}
	at net.smileycorp.hordes.client.render.ZombiePlayerRenderer.m_7392_(ZombiePlayerRenderer.java:24) ~[The-Hordes-1.20.1-1.3.2b.jar%23767!/:1.20.1-1.3.2b] {re:classloading}
```
